"""Flattens Borr Drilling's vector logo (Wikimedia Commons "Borr Drilling logo.svg", taken from the company's 2021
sustainability report) into absolute paths, splits it into its parts and writes:
  lib/logo.ts                       the 18 triangles of the mark (with centres) and the two wordmark lines
  public/brand/logo-{blue,white,abyss}.svg   transparent full lock-ups
  app/icon.svg                      the mark alone, for the favicon
Usage: python3 scripts/logo.py [path/to/logo.svg]   (needs: pip3 install svgelements)"""
import json, sys
from svgelements import SVG, Path

src = sys.argv[1] if len(sys.argv) > 1 else "_scrape/logo-commons.svg"
svg = SVG.parse(src, reify=True)
paths = [e for e in svg.elements() if isinstance(e, Path) and e.values.get("fill") not in (None, "none") and len(e) > 0]
# the clip rects in <defs> are not drawn; real shapes carry the brand fill
paths = [p for p in paths if str(p.fill).lower() != "none" and p.bbox() is not None]
boxes = [(p, p.bbox()) for p in paths]
x0 = min(b[0] for _, b in boxes); y0 = min(b[1] for _, b in boxes)
x1 = max(b[2] for _, b in boxes); y1 = max(b[3] for _, b in boxes)
S = 100 / (y1 - y0)  # normalise height to 100

def norm(p):
    q = Path(p)
    q *= f"scale({S}) translate({-x0},{-y0})"
    q.reify()
    return q

marks, words = [], []
items = []
for p, b in boxes:
    q = norm(p)
    bb = q.bbox()
    items.append({"d": q.d(), "cx": round((bb[0] + bb[2]) / 2, 2), "cy": round((bb[1] + bb[3]) / 2, 2), "x": round(bb[0], 2), "x2": bb[2]})
# the mark and the wordmark are separated by the widest horizontal gap in the lock-up
xs = sorted(items, key=lambda i: i["x"])
gap = max(range(1, len(xs)), key=lambda k: xs[k]["x"] - max(i["x2"] for i in xs[:k]))
split = xs[gap]["x"]
for i in items:
    i.pop("x2")
    (marks if i["x"] < split else words).append(i)

# wordmark lines: "Borr" sits above "Drilling"
mid = sum(w["cy"] for w in words) / len(words)
borr = sorted([w for w in words if w["cy"] < mid], key=lambda w: w["x"])
drilling = sorted([w for w in words if w["cy"] >= mid], key=lambda w: w["x"])
# order the mark ring by angle around its centre so it can build like a clock
import math
mx = sum(m["cx"] for m in marks) / len(marks); my = sum(m["cy"] for m in marks) / len(marks)
for m in marks:
    m["r"] = round(math.hypot(m["cx"] - mx, m["cy"] - my), 2)
    m["a"] = round(math.degrees(math.atan2(m["cy"] - my, m["cx"] - mx)), 1)
marks.sort(key=lambda m: ((m["a"] + 90) % 360))
W = round((x1 - x0) * S, 2)
markW = round(max(float(Path(m["d"]).bbox()[2]) for m in marks), 2)
print(len(marks), "triangles,", len(borr), "+", len(drilling), "wordmark shapes, viewBox", W, "x 100, mark width", markW)

clean = lambda l: [{k: v for k, v in i.items() if k != "x"} for i in l]
ts = "// Generated by scripts/logo.py from Borr Drilling's vector logo (Wikimedia Commons, 2021 sustainability report).\n"
ts += f"// Height normalised to 100. The mark's 18 triangles are ordered clockwise from 12 o'clock; cx/cy is each centre,\n// r and a its distance and angle (deg) from the ring's centre ({mx:.2f}, {my:.2f}).\n"
ts += f"export const LOGO_W = {W};\nexport const LOGO_H = 100;\nexport const MARK_W = {markW};\n"
ts += f"export const MARK_CENTRE = [{mx:.2f}, {my:.2f}] as const;\n"
ts += "export const MARK = " + json.dumps(clean(marks), indent=0) + " as const;\n"
ts += "export const WORD_BORR = " + json.dumps([w["d"] for w in borr], indent=0) + " as const;\n"
ts += "export const WORD_DRILLING = " + json.dumps([w["d"] for w in drilling], indent=0) + " as const;\n"
open("lib/logo.ts", "w").write(ts)

def lockup(fill):
    ds = [m["d"] for m in marks] + [w["d"] for w in borr + drilling]
    return f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} 100"><title>Borr Drilling</title><g fill="{fill}">' + "".join(f'<path d="{d}"/>' for d in ds) + "</g></svg>\n"
import os
os.makedirs("public/brand", exist_ok=True)
for name, fill in (("blue", "#0069FF"), ("white", "#FFFFFF"), ("abyss", "#082835")):
    open(f"public/brand/logo-{name}.svg", "w").write(lockup(fill))
# Favicon: the mark alone in Borr blue on a transparent square (as the live favicon.ico), cropped tight around the
# ring and centred on it, so the triangles stay legible at 16px.
from svgelements import Path as _P
bb = [_P(m["d"]).bbox() for m in marks]
fx0, fy0 = min(b[0] for b in bb), min(b[1] for b in bb); fx1, fy1 = max(b[2] for b in bb), max(b[3] for b in bb)
side = max(fx1 - fx0, fy1 - fy0) * 1.04
cx, cy = (fx0 + fx1) / 2, (fy0 + fy1) / 2
vb = f"{cx - side / 2:.2f} {cy - side / 2:.2f} {side:.2f} {side:.2f}"
icon = f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="{vb}"><g fill="#0069FF">' + "".join(f'<path d="{m["d"]}"/>' for m in marks) + "</g></svg>\n"
# Apple touch icon source: the same mark on Abyss, with room around it (iOS masks the corners itself).
side2 = side * 1.5
vb2 = f"{cx - side2 / 2:.2f} {cy - side2 / 2:.2f} {side2:.2f} {side2:.2f}"
apple = f'<svg xmlns="http://www.w3.org/2000/svg" width="180" height="180" viewBox="{vb2}"><rect x="{cx - side2 / 2:.2f}" y="{cy - side2 / 2:.2f}" width="{side2:.2f}" height="{side2:.2f}" fill="#082835"/><g fill="#0069FF">' + "".join(f'<path d="{m["d"]}"/>' for m in marks) + "</g></svg>\n"
open("_scrape/apple-icon.svg", "w").write(apple)
open("app/icon.svg", "w").write(icon)
