"""Turns the live site's triangle world map (world_map.png) into vector data: one entry per triangle with its centre
and the way it points. Output: lib/map.ts. Usage: python3 scripts/map.py [path/to/world_map.png]"""
import json, sys
import numpy as np
from PIL import Image
from scipy import ndimage

src = sys.argv[1] if len(sys.argv) > 1 else "_scrape/world_map.png"
a = np.array(Image.open(src).convert("RGBA"))[:, :, 3] > 90
lab, n = ndimage.label(a)
H, W = a.shape
pts = []
for i, sl in enumerate(ndimage.find_objects(lab), 1):
    ys, xs = np.nonzero(lab[sl] == i)
    if len(xs) < 6:
        continue
    cx, cy = xs.mean() + sl[1].start, ys.mean() + sl[0].start
    bx = (sl[1].start + sl[1].stop - 1) / 2
    # a right-pointing triangle carries its mass on the left of its box
    d = 1 if cx < bx else -1
    pts.append((round(cx, 1), round(cy, 1), d))
pts.sort(key=lambda p: (p[1], p[0]))
out = "// Generated by scripts/map.py from the live site's world_map.png (" + f"{W}x{H}" + "): x, y, direction (1 right, -1 left).\n"
out += f"export const MAP_W = {W};\nexport const MAP_H = {H};\n"
out += "export const MAP_POINTS: readonly (readonly [number, number, 1 | -1])[] = " + json.dumps(pts, separators=(",", ":")) + ";\n"
open("lib/map.ts", "w").write(out)
print(len(pts), "triangles", sum(1 for p in pts if p[2] == 1), "right")
